### PR TITLE
Convert the project to c2cwsgiutils

### PR DESCRIPTION
**Pull request by pvalsecc**

### CODE REVIEW

**Comment by pvalsecc** [comment]
Tested with saccas_suissealpine

**Comment by asaunier** [comment]
@pvalsecc Please rather ask to @arnaud-morvan who is the author of the initial c2corg_images backend.

**Comment by gberaudo** [comment]
@pvalsecc, can it waits tomorrow for merging?

**Comment by pvalsecc** [comment]
Why your are afraid it will report too many errors in the next release? ;-)
Yes, it can wait.

**Pull request merged**
